### ISSUE TITLE
[Bug] NoSuchFieldException

### ISSUE THREAD

**Issue by 3Lord3** [ASangarin/Breaker#6]
**Describe the bug**
Every time I break a stone, I get a warning in the console. The configs are standard

```
[23:21:16 WARN]: java.lang.NoSuchFieldException: X
[23:21:16 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2489)
[23:21:16 WARN]:        at com.asangarin.breaker.nms.NMSHandler_1_16_R3.getBlockBreakSound(NMSHandler_1_16_R3.java:66)
[23:21:16 WARN]:        at com.asangarin.breaker.core.BreakingBlock$1.run(BreakingBlock.java:49)
[23:21:16 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[23:21:16 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[23:21:16 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1378)
[23:21:16 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397)
[23:21:16 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1287)
[23:21:16 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1012)
[23:21:16 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[23:21:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
```

**To Reproduce**
1. Prepare a server like mine
2. Break stone

**Expected behavior**
No errors

**Server Version:**
git-Yatopia-6 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugin Version:**
1.3.1, free

**Additional context**
Plugins: BetterEconomy, BreakerLite, CustomCrafting, ExtraHardMode, F3Name, ItemJoin, lightEconomy, LuckPerms, NBTAPI, OpenRP, PlaceholderAPI, ProtocolLib, PwnPlantGrowth, ShokoNameHide, SimpleRename, TAB, Towny, UltraCustomizer, Vault, WolfyUtilities

**Comment by ASangarin** [comment]
This has been fixed in Breaker premium. Will have to wait for Minecraft 1.17 and Premium Breaker to be updated, before a free version compatible with 1.16.5 will be released.
